config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post 'get_poke'       , to: 'pokemon#get_poke'

  get  'exchanges'      , to: 'exchange#index'
  post 'valid_exchange' , to: 'exchange#valid_exchange'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Response
  include ExceptionHandler

end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  # Define custom error subclasses - rescue catches `StandardErrors`
  class AuthenticationError < StandardError; end
  class MissingToken < StandardError; end
  class InvalidToken < StandardError; end

  included do
    # Define custom handlers
    rescue_from ActiveRecord::RecordInvalid, with: :four_twenty_two
    rescue_from ExceptionHandler::AuthenticationError, with: :unauthorized_request
    rescue_from ExceptionHandler::MissingToken, with: :four_twenty_two
    rescue_from ExceptionHandler::InvalidToken, with: :four_twenty_two

    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end
  end

  private

  # JSON response with message; Status code 422 - unprocessable entity
  def four_twenty_two(e)
    json_response({ message: e.message }, :unprocessable_entity)
  end

  # JSON response with message; Status code 401 - Unauthorized
  def unauthorized_request(e)
    json_response({ message: e.message }, :unauthorized)
  end

end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/exchange_controller.rb
class ExchangeController < ApplicationController

  def index
    @trades = Trade.all.order(created_at: :desc)
  end

  def valid_exchange
    @first_team = build_team(params["first"])
    @second_team = build_team(params["second"])

    trade = Trade.new(first_team: @first_team, second_team: @second_team)

    if !@first_team.present? || !@second_team.present?
      flash.alert =  "Troca injusta =("
    elsif base_experience_compare(@first_team, @second_team) < 50
      flash.notice = "Troca justa =)"
      trade.is_valid = true
      trade.save
    else
      flash.alert =  "Troca injusta =("
      trade.is_valid = false
      trade.save
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def build_team(data)
    team = (1..6).map do |index|
      next unless data[index.to_s]["name"].present?

      {
        name: data[index.to_s]["name"],
        poke_img: data[index.to_s]["poke_img"],
        base_experience: data[index.to_s]["base_experience"]
      }
    end

    team.compact
  end

  def build_base_experience_sum(data)
    data.map{ |team| team[:base_experience].to_i }.sum
  end

  def base_experience_compare(first_team, second_team)
    first_base = build_base_experience_sum(first_team)
    second_base = build_base_experience_sum(second_team)

    (first_base - second_base).abs
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController

  def get_poke
    if poke_response_ok?
      name = params[:poke_name]
      base_experience = poke_response_poke["base_experience"]

      response = {name: name, base_experience: base_experience, url_img: get_poke_img, status: "OK"}
    else
      response = {status: "NOK"}
    end

    json_response(response)
  end

  private

  def get_url
    @get_url ||= PokeApiService.get_url(params[:poke_name])
  end

  def get_poke_img
    @get_poke_img ||= PokeApiService.get_poke_img(poke_response_poke["id"])
  end

  def poke_api_request_poke
    @poke_api_request_poke ||= PokeApiService.new(api_url: get_url)
  end

  def poke_response_ok?
    poke_api_request_poke.response_ok?
  end

  def poke_response_poke
    poke_api_request_poke.response_body
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchange/_team.html.erb
<div class="team" data_key=<%= key %>>

  <div class="title"><%= title %></div>

  <div class="team_box">
    <% team.each do |poke| %>
      <div class="item">
        <div class="content">
          <div class="poke_name"><%= poke["name"] %></div>
          <div class="poke_img_box"><%= image_tag(poke["poke_img"], class: "poke_img") %></div>
          <div class="base_experience"><%= poke["base_experience"] %></div>
        </div>
      </div>
    <% end%>
  </div>

</div>

app/views/exchange/index.html.erb
<div id="exchanges">

  <div class="exchanges_box">

    <% @trades.each do |trade| %>
      <div class="exchange_box <%= trade.is_valid ? 'valid' : 'invalid' %>">
        <div class="first_team">
          <%= render partial: 'team', locals: {key: 'first', title: 'Primeiro Time', team: trade.first_team} %>
        </div>

        <div class="exchange_btn">
          <div class="exchange_icon">
            <% if trade.is_valid %>
              <i class="fas fa-check"></i>
            <% else %>
              <i class="fas fa-times"></i>
            <% end %>
          </div>
        </div>

        <div class="second_team">
          <%= render partial: 'team', locals: {key: 'second', title: 'Segundo Time', team: trade.second_team} %>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/home/_search_modal.html.erb
<div class="search_modal">
  <div class="search_box">
    <%= text_field_tag "poke_search_#{team}_#{key}", nil, class: 'search_field', placeholder: 'Procure o pokémon...' %>
    <%= button_tag 'Procurar', type: 'button', class: 'search_btn' %>
    <div class="error">Este pokémon não foi encontrado</div>
  </div>
</div>

app/views/home/_team.html.erb
<div class="team" data_key=<%= key %>>

  <div class="title"><%= title %></div>

  <div class="team_box">
    <% (1..6).each do |index| %>
      <div class="item empty" data_key=<%= index %>>
        <%= hidden_field_tag "#{key}[#{index}][name]", nil, class: "poke_name" %>
        <%= hidden_field_tag "#{key}[#{index}][poke_img]", nil, class: "poke_img" %>
        <%= hidden_field_tag "#{key}[#{index}][base_experience]", nil, class: "base_experience" %>

        <div class="content"><i class="fas fa-plus"></i></div>
        <%= render partial: 'search_modal', locals: {key: index, team: key} %>
      </div>
    <% end%>
  </div>

</div>

app/views/home/index.html.erb
<div id="home">
  <div class="exchange_box <%= 'valid' if flash[:notice].present? %> <%= 'invalid' if flash[:alert].present? %>">

    <div class="flash_message">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    </div>


    <%= form_tag(valid_exchange_path, id: "exchange_form", class: "exchange_form") do %>

      <div class="first_team">
        <%= render partial: 'team', locals: {key: 'first', title: 'Primeiro Time'} %>
      </div>

      <div class="exchange_btn">
        <%= button_tag(type: 'submit', class: "exchange_btn_field") do %>
          <div class="exchange_icon"><i class="fas fa-sync-alt"></i></div>
          <div class="label">Trocar</div>
        <% end %>
      </div>

      <div class="second_team">
        <%= render partial: 'team', locals: {key: 'second', title: 'Segundo Time'} %>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeTrader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7c78c8b106.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'partials/header' %>

    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<header>
  <div class="title">Poke Trader</div>

  <nav>
    <div class="item"><%= link_to('Nova Troca', root_path) %></div>
    <div>|</div>
    <div class="item"><%= link_to('Histórico de trocas', exchanges_path) %></div>
  </nav>
</header>